# Generated by Django 2.2.7 on 2019-11-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_auto_20191113_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='blog',
            name='field1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='field10',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='field2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='field3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='field4',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='field5',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='field6',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='field7',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='field8',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='field9',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='image_folder'),
        ),
    ]
